=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/.schema/v1/relation.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Relation",
  "description": "A named association between entities.",
  "type": "object",
  "x-order": [
    "$schema",
    "kind",
    "id",
    "name",
    "displayName",
    "pluralName",
    "package",
    "inverseName",
    "relationKind",
    "description",
    "stereotypes",
    "tags",
    "category",
    "ends",
    "attributes",
    "allowDuplicates",
    "properties",
    "generation",
    "source"
  ],
  "properties": {
    "$schema": {
      "$ref": "common.json#/$defs/schemaPath"
    },
    "kind": {
      "const": "relation"
    },
    "id": {
      "$ref": "common.json#/$defs/id"
    },
    "name": {
      "$ref": "common.json#/$defs/label",
      "default": ""
    },
    "displayName": {
      "type": "string"
    },
    "pluralName": {
      "type": "string"
    },
    "package": {
      "$ref": "common.json#/$defs/id"
    },
    "inverseName": {
      "type": "string",
      "minLength": 1
    },
    "relationKind": {
      "enum": ["association", "aggregation", "composition", "n-ary"],
      "default": "association"
    },
    "description": {
      "$ref": "common.json#/$defs/description"
    },
    "stereotypes": {
      "$ref": "common.json#/$defs/keyList",
      "default": []
    },
    "tags": {
      "$ref": "common.json#/$defs/tagList",
      "default": []
    },
    "category": {
      "$ref": "common.json#/$defs/id"
    },
    "ends": {
      "type": "array",
      "items": {
        "title": "Relation end",
        "type": "object",
        "x-order": ["id", "entity", "role", "navigation", "displayName", "pluralName", "min", "max", "onDelete", "ordered", "description"],
        "properties": {
          "id": {
            "$ref": "common.json#/$defs/id"
          },
          "entity": {
            "$ref": "common.json#/$defs/id"
          },
          "role": {
            "$ref": "common.json#/$defs/identifier"
          },
          "navigation": {
            "description": "Property name generated on the opposite entity; empty means not navigable from there.",
            "anyOf": [
              {
                "$ref": "common.json#/$defs/identifier"
              },
              {
                "const": ""
              }
            ],
            "default": ""
          },
          "displayName": {
            "type": "string"
          },
          "pluralName": {
            "type": "string"
          },
          "min": {
            "enum": [0, 1],
            "default": 0
          },
          "max": {
            "enum": [1, "*"],
            "default": "*"
          },
          "onDelete": {
            "enum": ["none", "cascade", "restrict", "set-null"],
            "default": "none"
          },
          "ordered": {
            "type": "boolean",
            "default": false
          },
          "description": {
            "type": "string"
          }
        },
        "required": ["id", "entity", "role"],
        "additionalProperties": false
      },
      "minItems": 2
    },
    "attributes": {
      "type": "array",
      "x-sort": "order",
      "items": {
        "$ref": "common.json#/$defs/attribute"
      },
      "default": []
    },
    "allowDuplicates": {
      "type": "boolean",
      "default": false
    },
    "properties": {
      "$ref": "common.json#/$defs/properties",
      "default": {}
    },
    "generation": {
      "$ref": "common.json#/$defs/generation",
      "default": {}
    },
    "source": {
      "$ref": "common.json#/$defs/source"
    }
  },
  "required": ["kind", "id", "name", "ends"],
  "additionalProperties": false
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/agreement-line-is-for-product.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M298XZCQYBXG0KHPBST6VG4J",
  "name": "agreement line is for product",
  "package": "01M1DE7C8B6C6SJ56R6QBZQJBT",
  "description": "Covered product.",
  "category": "01M1DAV43K3Q185051SG2CRJSN",
  "ends": [
    {
      "id": "01M2BJC4ADYZPY7NP7A7Z5CJQ2",
      "entity": "01M20RAEF2QZ5W8HV57RBX5PQV",
      "role": "product",
      "navigation": "product",
      "max": 1,
      "onDelete": "set-null"
    },
    {
      "id": "01M20M59YDB4FPTV3J1FFTWCTQ",
      "entity": "01M23MARQX94BHXK3Y4EB4Q77C",
      "role": "agreementLines"
    }
  ]
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/order-hold-released-by.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M1Y6DS5FG8RYMSF9H137R7K2",
  "name": "order hold released by",
  "package": "01M28AC84B1SVDDC2EY42YJNZ8",
  "description": "Who released it.",
  "category": "01M1DDZYJWHS2VRM9BAYTT4SKZ",
  "ends": [
    {
      "id": "01M21DV79V1M4H0M8S33V1T3J4",
      "entity": "01M2CMF5JR3GW828G267AZ0M1E",
      "role": "releasedBy",
      "navigation": "releasedBy",
      "max": 1,
      "onDelete": "set-null"
    },
    {
      "id": "01M2V5BVM5VVA64XRDT9DGQNGD",
      "entity": "01M1GGGF7MKSKSSN9E4MQGWNG4",
      "role": "orderHolds"
    }
  ]
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/supplier-quote-supplier.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M2WGRSPAVT3FQ03ZCEJDH3JJ",
  "name": "supplier quote supplier",
  "package": "01M1HBJ9DHC9YMPY1A6RCV4TTG",
  "description": "Quoting supplier.",
  "category": "01M1Z1CM7DCRF0KE9WXCPSYXSX",
  "ends": [
    {
      "id": "01M2F34XR12AXMJM9SXC0RF87Z",
      "entity": "01M2A5WW8NFWJS1V5NFRKCBNYV",
      "role": "supplier",
      "navigation": "supplier",
      "min": 1,
      "max": 1,
      "onDelete": "restrict"
    },
    {
      "id": "01M35AFVZDCC5KA87GWXS9K7CB",
      "entity": "01M2XJ2JS9QHPBPRS652GKRX01",
      "role": "supplierQuotes"
    }
  ]
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/cart-user-account.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M1KEH6QCFA1FWG0NNAHM658H",
  "name": "cart user account",
  "package": "01M28AC84B1SVDDC2EY42YJNZ8",
  "description": "Portal user who owns the cart.",
  "category": "01M1DDZYJWHS2VRM9BAYTT4SKZ",
  "ends": [
    {
      "id": "01M1YD2A8SDDYHZ857C51Z60FB",
      "entity": "01M2CMF5JR3GW828G267AZ0M1E",
      "role": "userAccount",
      "navigation": "userAccount",
      "min": 1,
      "max": 1,
      "onDelete": "restrict"
    },
    {
      "id": "01M313QG6XD38HWRSWKZZ6DXF1",
      "entity": "01M1G2XC8VHF50WCS54G3Y5R96",
      "role": "carts"
    }
  ]
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/goods-receipt-line-is-for-product.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M2HG0N4W4NYE2PRGWXJHWG2Y",
  "name": "goods receipt line is for product",
  "package": "01M1HBJ9DHC9YMPY1A6RCV4TTG",
  "description": "Product received.",
  "category": "01M1Z1CM7DCRF0KE9WXCPSYXSX",
  "ends": [
    {
      "id": "01M35XBHA95B760119WKMS6W0D",
      "entity": "01M20RAEF2QZ5W8HV57RBX5PQV",
      "role": "product",
      "navigation": "product",
      "min": 1,
      "max": 1,
      "onDelete": "restrict"
    },
    {
      "id": "01M2WRKEKBYD61SWVVMJX57AVF",
      "entity": "01M2GBMZTV29WK7A5V2BAQSNCF",
      "role": "goodsReceiptLines"
    }
  ]
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/party-note-author.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M1VZCDDPNE9056VDTXVNWEWS",
  "name": "party note author",
  "package": "01M1EN9FE0DH7N8JWD10TVDZ9A",
  "description": "Who wrote the note.",
  "category": "01M2T4A01BB6EGWR7CP8AM5WFQ",
  "ends": [
    {
      "id": "01M29JY177Z21WQZ2KNFAAJAJD",
      "entity": "01M2CMF5JR3GW828G267AZ0M1E",
      "role": "author",
      "navigation": "author",
      "max": 1,
      "onDelete": "set-null"
    },
    {
      "id": "01M2XTBGM491Q227JNX7GPSEZ0",
      "entity": "01M1KJSJ5XRC8BCYTQT8DNYWHD",
      "role": "partyNotes"
    }
  ]
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/cycle-count-lines.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M28RYW1CCMNZBZKM97SQFF4B",
  "name": "cycle count lines",
  "package": "01M1KRHM5ECKGZXYXAD5RVR3SY",
  "relationKind": "composition",
  "description": "Locations and products to count.",
  "category": "01M23SKM8QFT1AZMAWCDFTJRMS",
  "ends": [
    {
      "id": "01M34T1GTFAX72MHFMBM6A3Z20",
      "entity": "01M2NGDKC9XHW37BDXATNQ314D",
      "role": "cycleCount",
      "navigation": "cycleCount",
      "min": 1,
      "max": 1,
      "onDelete": "cascade"
    },
    {
      "id": "01M2WRB5SDW684FDT8D1NJAZ2P",
      "entity": "01M21Y0KVFX1RBJ8PW4RYPAV3T",
      "role": "lines",
      "navigation": "lines"
    }
  ]
}

=== mattjcowan/maquettiste/samples/reference-app/.maquettiste/model/relations/lead-converts-to-converted-customer.json
{
  "$schema": "../../.schema/v1/relation.json",
  "kind": "relation",
  "id": "01M25XA3HH3VDBW2HQQFNTHV08",
  "name": "lead converts to converted customer",
  "package": "01M1EN9FE0DH7N8JWD10TVDZ9A",
  "description": "Customer created from the lead.",
  "category": "01M2T4A01BB6EGWR7CP8AM5WFQ",
  "ends": [
    {
      "id": "01M28F54XJZ23K925C747QBQMX",
      "entity": "01M1ECZKYNSKVNCWW2XM34E20X",
      "role": "convertedCustomer",
      "navigation": "convertedCustomer",
      "max": 1,
      "onDelete": "set-null"
    },
    {
      "id": "01M1ZSCXXHM2MA67EW63TMPNMP",
      "entity": "01M2QFZSC4KWD20CENXN364C9Y",
      "role": "leads"
    }
  ]
}
